### ISSUE TITLE
switch CTL to using RFG - Circulate Heroku

### ISSUE THREAD

**Issue by rkim00** [chicago-tool-library/circulate#203]
do this after PHR collaboration, but before Hacktoberfest

**Comment by benlangfeld** [comment]
Are there any notes on how you plan to do this, or on how much the current CTL deployment has diverged from the current development branch? There are some data migrations for #114 that we'll have to take this move into consideration for, and the schema might not be compatible in order to do a straight DB import. /cc @jim @pollygee
